/// Flutter icons KmelloIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  KmelloIcons
///      fonts:
///       - asset: fonts/KmelloIcons.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class KmelloIcons {
  KmelloIcons._();

  static const _kFontFam = 'KmelloIcons';
  static const String? _kFontPkg = null;

  static const IconData referidor = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vendedor_aficionado = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vendedor_profesional = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData consultar = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redimir = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vender = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cerrar_sesion = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData configuraciones = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mis_datos = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData termino_condiciones = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData academia = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData agendas = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beneficios = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cobros = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData productos = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData prospectos = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData solucitudes = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData venta_comision = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codigo_de_verificacion = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contrasena = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData correo_electronico = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData registrarse = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData validar_identidad = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData agenda = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData capacitacion = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData consultar_productos = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData estado_de_cuenta = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mis_clientes = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mi_perfil = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData suscripciones = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seguros = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credito_corporativo = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData creditos = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData planes_exequiales = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medicina_prepagada = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seguro_vehiculo = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData consumo = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credito_hipotecario = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credito_vehiculo = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData productivo = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xf09a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube = IconData(0xf167, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xf16d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsapp = IconData(0xf232, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
