/// Flutter icons KmelloIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  KmelloIcons
///      fonts:
///       - asset: fonts/KmelloIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class KmelloIcons {
  KmelloIcons._();

  static const _kFontFam = 'KmelloIcons';
  static const String? _kFontPkg = null;

  static const IconData icon_comprar_p_1 = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_redimir_1 = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_consultar = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData codigo_de_verifiacion = IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contrasen_a = IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData registrarse = IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData validar_identidad = IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData consultar_productos = IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mi_perfil = IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mis_clientes = IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData capacitacion = IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData estado_de_cuenta = IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData agenda = IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
